version: "3.9"
services:
  app:
    build:
      context: .
      target: build
    environment:
      - ENV_NAME=local
  localstack:
    image: localstack/localstack:0.12.16
    ports:
      - 4566:4566
    environment:
      SERVICES: sqs
      HOSTNAME: localstack
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"